# Generated by Django 5.2.7 on 2025-11-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_advertencia_coordenador_coordenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertencia',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada')], default='em_andamento', max_length=20),
        ),
    ]
