# Generated by Django 5.2.7 on 2025-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_advertencia_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='turmas',
            field=models.ManyToManyField(blank=True, related_name='professores', to='usuarios.turma'),
        ),
    ]
