# Generated by Django 5.2.7 on 2025-11-25 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_nota_bimestre_secretaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(default='Diretor', max_length=50)),
                ('unidade', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
