# Generated by Django 5.2.7 on 2025-11-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_diretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diretor',
            name='unidade',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='cargo',
            field=models.CharField(default='Direção', max_length=50),
        ),
    ]
