# Generated by Django 5.2.7 on 2025-12-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_remove_diretor_unidade_secretaria_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertencia',
            name='descricao_ocorrido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertencia',
            name='responsavel_presente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
