# Generated by Django 5.2.7 on 2025-12-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_advertencia_descricao_ocorrido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenador',
            name='cargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='setor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
