# Generated by Django 4.2.16 on 2026-02-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_coordenador_cargo_coordenador_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
    ]
